version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs-dev
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    networks:
      - teamix-backend

  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teamix-backend

  redis:
    container_name: redis
    image: redis:6.2
    restart: always
    env_file:
      - .env
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - teamix-backend

volumes:
  postgres_data:
  redis_data:

networks:
  teamix-backend:
