version: '3.7'

services:
    db:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - teamix-backend

    redis:
        container_name: redis
        image: redis:6.2
        restart: always
        ports:
            - 6379:6379
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - teamix-backend

    localstack:
        container_name: localstack
        image: localstack/localstack
        ports:
            - "4566:4566" 
        environment:
            - DEBUG=${DEBUG:-0}
        volumes:
            - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - teamix-backend


volumes:
    postgres_data:
    redis_data:

networks:
    teamix-backend: